language: c
sudo: false
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  matrix:
    secure: 3xPKmZCpw1uxMP9pxu7Muin46wn+JGEklUrbqXSew/rCY46HIk+WNE/PvHnt5mJm/ie1WsCGT0fMCP6QGPFeWvscljw4zzrPMRBU9HATYIGnTSmH18kWD3keTSExrIL3ho8xgdGkz6V7JTVJZmU2yHod3TjbRO+Z+Bc2sgxwbfLrYdo+dqV9RwCijv87IIHPAhmrvp+5kBZac5Jjzxtw/MDXgO2dmF2LvnYNOO1M+apUCifrv5WcVsBGxyMACewNqTwdHAasaGuZ6qRoVoTYegiRDk557KfdkurSEHEJNqCc3tXfUbduxYN/8MU1NCHLFKqMZaGNr9CD8JjCJumvpN/JYoRAqyreoFloGN6cFLTdmlsTohRk3KiruNM5UyXBDOF9QH5X+G3FlgpDq2IAt/dSfbCeGBzBnDTZu50dWg4Zc8+qSfoj+CGUN4TUb4/XliD7v0oZ7HAHiIlALq+PXYefAItO510yQBmv2QuvEZ/O+A/8079XS0/BxLAolPBIH3Ac08tp59f4clEVSB/mhZO2EwBe6IAz0Ld9hIeGzFnbsmKEh4BulHUGtAdEIqQXT9ks1jyx08s0vV9ttaXbuuvoM6zhIYsOm5U1cDADxNa8fJjTFhC1p4Cehk/aRasXcN2ZWNIfLFGO7KPGjHOWOjQezzFVm4TRyGVcc0Mbu8M=
