language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: fL73rWd8rx0Cu4lAR9Gc6sLw0+NnXttBS7orijUseq6p6atKWApIwDb9TZR29fUowns0vhxC22NZjS119bTQRyA68z7WvCfMWr9/fviavFAWxVIbfWbJ6kypLgpWIPFAY+Qbn7d40YQdA9QGaj+fkesiVXrBxvxbJ/HRCqiQ7+pUVDxb1cjv6e9X5wR2uF+UnN7cCuT5oEJw6ZXM9Xl4jh5k6wNOz3SdHzA/292qCb+2lsyG/0jbfOky2tJ2dCrg9/xkhxs17ViOpqUu3VkOhP+B+SIcgAXncxZ+V4fZHwo0Kq8JnbuVvL9o+Nr+EFXGapxAUeQgwmnN8rzKDTofAZ3RW+Zq6NnPVI/97UVIxa2+zK2QzmPD653lOMg3+2+PxX5ZcGFRvwz/b2sAjb4JeGsi7tkaALKF+jOobC5dv/LzjveDswhNzu/A4vO+3jjKHZvfjWz8na/57fG13untwBJQYSPhSKCx3GTb6yUczq+y9ctelEJwG0wyjTbkTztOU5zV24bT71WPFLez2tR2zyH99e2/KLnNQ6o0X0XU0dlr2CY1Lv/waVnh9mt0mPY+b3OUR+DhUMjBlF+wRaTIhsgGPj6Pp+NAIA+tsLW4a1VY7z08XwgJVnRlF6UI6j8YEjo6mpvr1U3AbVueGEP0LuS/70px1RvdNe2hpMPtl8c=
