language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: WLjG/XENSMHt0enPGTMSkSfOLFBGGQNiPU+kAk1DEN4v0L0S8NGxpIBT4UispVcPST1b5oK5PekHiDRrUreC37c2H0bXGFtJEw9pkaxLQA1vKqU6TlOqrf+d0K3cm4IISPQsUEPLsD4HG5BmtDxt2pbhf8HSjFD26yejS9nK5efhiYKLI5WCGV2z5ktKiWp8p4aXm3SN99N1j6pvvevLhmYJxIr2CEipgTzul+3B1WiAiTGiAEG6W54KRxvnhclO2wzZLB2uJi57+cDab9yFkXX0Tpia2gw3clufMVkfUXnTbrvZN0KOzcf0Xxz0qZV+ngp2C7x1s7ci+ZWVi5lZvP9faq5O76MXlBsDa7sjce3fb8F16NiYSWxsZk2IXnqgeBipWQu1lDiFVnC+W3zDKgDlg3ZTguUBH8dXVd3bt7ymy9VBxNqFnEMMque9RzlQxzJKowQd0K7H8aXJSOZCPtyFw8sAmsghPIRWOQLVsFDW3FxQSLpaN18yVi5JaJo0D3V3UpHnL77bZzkCnos9FTNb6PYSfUz6HPF5DQ0x+EGMcCkxu4x6G3/pOb6UxfG+NUkA9VBoGnjcVnPSQZAHGAe+NhpcbRcj55vkSmN84jU0ndXMlN5jSf5jJlvt/bNRV5BVkTFQQp/X1Q5WNhUu/kVzPjOhg45tYjxA+pTS9uw=
