language: c
sudo: false
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  matrix:
    secure: lTpl7Pe6aH3IJ1CLSg63yODLDCXIM9853GOvpv0tXxaG6ic1ZphOJU1oTWi3ntNt34Gifr2XOC/uI9QO0NnfwGc+tBucpB9QmwZP4H6nE3Izb/QAc3QR8eiRwWtNTdYCXkaRgX01m4iB1mRjuhisGvgglRm5WufYdYAYWD7YzNNaW13YM/0TQYN0zAFqs2FtCtGlhjx80ghxiuCc9ig/e20EFhNxSSOqrctGM4K/KGkNfpusqy7cWYFnTIZNNjdK3qgQkjDQYcPrK0GLQrOTJ1PWTV2m79O/Sf8sgBJAYTlidAK/oqWPuW9aFDGe6/boUHbt1d6yGJoGPCQb6Hip84yxpjfpwTb3i8O6jkTVG3KqZmNamceDtLbp6ngsg6MfktrBaZ82uQVHOd9PKsmPynUAbBIRQmy3OtkiT5DJYc1inEQJ8ilCtE0bRDDKslJNgPjLkB2pmz+R2iw4ibrsKliQA5UMyBArxA3Jh+QWMZKo4PODlDgmd7hna7EyNLFTqMV5nzGRaOTEYSgu2Ttdig5sKVo4ovXl2h2HXRmQyOvAbOQxYlDy2vaW2O87rwF3rimzLM1kolqsJ2C7p5pGrfbv29mWdXAr35W/kfGULmEQlUX+nlpuxYzQEHY/5a0VuJz+trbzdwO7+87iwNassi3jqfB2IsWwbA/Xmum6nb0=
