language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: 0wAumHjNhgzW+hc+yg8r/9qzlCFYIuSGppNQl/OE3dRMMfx8O6z/f/cORC1WLxD0WB8990N9RXZ4JXM7R1/7pec5p/K2Jw1u/WyGQkDSr46cijH4/6QDWAga9Vun6tzYuHxv75A0t5b+EqUmRzKllyG2Y9ZD26ztlx3l768k4m++F+7dbg1lY/6X/7bxAFVNtQ5l2OaSueq8O952SN+YDquwTnSWS2KdraMOzTnGbyb32Xxx1Gipt340tTf47TPf5wpHT1f7FGqhszk6H+o4K3pTVTk9Agvx8T15BGsfk95hqTMvGaJwPZxOkqhey+Ot2O4ca1znWODbndC5o69DR444UJk3ehYhYIntu+c2hFWAHWI3xIxb1eD0PuQzkwcELSA4lKwCz4BQRThPu46Vs+RmTuVD7WYA/kgIzF5DurX/T5g1jqRDN4UOwlbMiG2KxY3MCxEkn2kOiIQXhP6l5Ij/szmQTx1+2facjagRCjJcnhuvYvOlBpftUNu7Vz0WbToe1yJQUjGd611R/jo4sPHaEIFuSUfv1YmiIt5zfE78Tma6zXkWrm60u8hXgXDFdjTdJzwHOqu+Nq9zVLlkYwfD2vLAH0XyGjEfmxwWTrHyOq6lKz0UYBfPC1rETxgu/DrrKcuppL0ZNpD6JZE7iRsJKKaBy1IYlR+Zbtb7Mu4=
